# Generated by Django 5.1 on 2024-08-26 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FichaJovenes',
            new_name='FichaJoven',
        ),
        migrations.RenameModel(
            old_name='PerfiUsuario',
            new_name='PerfilUsuario',
        ),
    ]
