# Generated by Django 5.1 on 2024-09-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_remove_perfilusuario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='es_ecargado',
            new_name='es_encargado',
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='canatidad_de_hijos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='fecha_de_nacimiento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='foto_del_joven',
            field=models.ImageField(upload_to='imagenes/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='nro_casa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='telcelular',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='telfijo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='tiempoobra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='whatsapp',
            field=models.IntegerField(null=True),
        ),
    ]
