# Generated by Django 5.1 on 2024-09-04 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_rename_es_ecargado_perfilusuario_es_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichajoven',
            name='usuarioqueregistro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ficha.perfilusuario'),
        ),
    ]
