# Generated by Django 5.1 on 2024-09-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_perfilusuario_id_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichajoven',
            name='fecapart',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='fecbautEspSanto',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='fechaingfju',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='fechaingiglesia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='foto_del_joven',
            field=models.ImageField(null=True, upload_to='imagenes/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='imagenantes',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fichajoven',
            name='imagendespues',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
