# Generated by Django 5.1 on 2024-10-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_alter_fichajoven_fecapart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEspiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fichajoven',
            name='grupoespiritual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ficha.grupoespiritual'),
        ),
    ]
